require 'getoptlong'

opts = GetoptLong.new(
  ['--l1-cpus', GetoptLong::OPTIONAL_ARGUMENT],
  ['--l1-memory', GetoptLong::OPTIONAL_ARGUMENT],
  ['--network-interface', GetoptLong::OPTIONAL_ARGUMENT],
  ['--l1-cpu-model', GetoptLong::OPTIONAL_ARGUMENT]
)

customParameter=''

puts "Original ARGV: #{ARGV}"
cpus = 4
memory = 16000
cpu_model = "host-model"
network_interface = "eth0"

opts.each do |opt, arg|
  case opt
  when '--l1-cpus'
    cpus = arg.to_i
  when '--l1-memory'
    memory = arg.to_i
  when '--l1-cpu-model'
    cpu_model = arg
  when '--network-interface'
    network_interface = arg
  end
end

puts "arg parse done"

Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-libvirt"
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "l1-linux" do |l1|
    l1.vm.hostname = "l1-linux"
    l1.vm.provider "libvirt" do |libvirt|
      libvirt.driver = "kvm"
      libvirt.nested = "true"
      libvirt.cpus = cpus
      libvirt.memory = memory
      libvirt.cpu_mode = cpu_model
    end

    # enable network bridge
    # Ref: https://developer.hashicorp.com/vagrant/docs/networking/public_network
    l1.vm.network "public_network", bridge: network_interface, dev: network_interface

    # provisoning
    # Run `vagrant provision` to apply the changes
    l1.vm.provision "file", source: "../l2-vagrant", destination: "/home/vagrant/l2-vagrant"
    l1.vm.provision "shell", path: "./init.sh", reboot: true
    l1.vm.provision "shell", path: "./init-user.sh", privileged: false
  end
end
