# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-libvirt"
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "l1-linux" do |l1|
    l1.vm.hostname = "l1-linux"
    l1.vm.provider "libvirt" do |libvirt|
      libvirt.driver = "kvm"
      libvirt.nested = "true"
      libvirt.cpus = 2
      libvirt.memory = 8000
    end

    # enable network bridge
    # Ref: https://developer.hashicorp.com/vagrant/docs/networking/public_network
    l1.vm.network "public_network", bridge: "enp7s0", dev: "enp7s0"

    # provisoning
    # Run `vagrant provision` to apply the changes
    l1.vm.provision "file", source: "../l0-vagrant", destination: "/home/vagrant/l0-vagrant"
    l1.vm.provision "shell", path: "./init.sh"
  end
end
