# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-libvirt"
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "l0-linux" do |l0|
    l0.vm.hostname = "l0-linux"
    l0.vm.provider "libvirt" do |libvirt|
      libvirt.driver = "kvm"
      libvirt.nested = "true"
      libvirt.cpus = 2
      libvirt.memory = 8000
    end
    l0.vm.provision "shell", path: "./init.sh"
  end

end
